### ISSUE TITLE
Backport and modify canvas customization from rtorrent-ps

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent-ps-ch#119]
Backport and modify canvas customization from `rtorrent-ps`.

**A. Tasks:**

Make all the columns configurable on the extended canvas except for Name and Tracker Domain columns:
- backport original canvas customization from rtorrent-ps
  - add new commands
  - add a multi-method for column rendering: `ui.column.render`
    - call those methods, order is determined by keys in the map as usual
    - keys in the map encode sorting + length + column title:  `sort:len:title`
    - chop rendered column title and contents to the specified length
  - make chopping of columns UTF8-aware: `u8_chop` internal method
  - make x-position of columns dynamic in the code (advance by header length)
- refactor existing complicated columns into commands, to make everything configurable (`d.ui.‹name›`) except for Name and Tracker Domain column
- create built-in default columns without having the need of any config file change, they can be:
  - disabled via config or on-the-fly
  - overridden via config or on-the-fly
- modify built-in colouring to work with certain columns
  - keep track all the positions of all the columns all the time
  - based on the label of columns, only these columns are colored: `⚑ `, `⣿ `, `☯ `, ` ⌬ ≀∆`, ` ⌬ ≀∇`
    - coloring of other built-in/custom columns aren't supported
  - keep applying color to the fixed Name and Tracker Domain columns

**B. Added commands:**

_Basic commands:_
- `value=«number»[,«base»]`: converts a given number with the given base (or 10 as the default) to an integer value
- `string.map=text,{from,to},…` for columns that can only have couple of fixed values, e.g. throttle, unsafe_data, etc.
- `d.tracker_scrape.downloaded` scrape info
- `d.tracker_scrape.complete` scrape info
- `d.tracker_scrape.incomplete` scrape info
- `d.parent_dir` to get the name of the parent directory of a download 
- `convert.human_size` used in upload data, data size columns
- `convert.magnitude` used in scrape columns

_The following commands return pre-formatted text for coloring purposes:_
- `d.ui.message` to return formatted text for message/tagged column
- `d.ui.completion` to return formatted text for completion column
- `d.ui.ratio` to return formatted text for ratio column
- `d.ui.uprate_tm`  to return formatted text for uprate/last_active_time column
- `d.ui.downrate_tm` to return formatted text for downrate/completed_time column

_Multi-commands:_
- `ui.column.render` multi-command to hold column definitions, usage:
  - to define a new column: use a new label that hasn't been used yet!
    - `method.set_key = ui.column.render, "230:1:◎", ((string.map, ((cat, ((d.custom,unsafe_data)))), {0, " "}, {1, "⊘"}, {2, "⊗"}))`
  - to disable a built-in default or custom column: use the same key of the column definition with no command defined 
    - `method.set_key = ui.column.render, "100:1:☢"`
  - to override a built-in default column: use the same key of the column definition with a new command
    - `method.set_key = ui.column.render, "200:1:⊘", ((string.map, ((d.throttle_name)), {"", " "}, {NULL, "∞"}, {slowup, "⊼"}, {tardyup, "⊻"}))` 
- `event.view.hide`, `event.view.show` multi commands to call them on view changes, usage:
  - `method.set_key = event.view.hide, ~log, ((print, ((ui.current_view)), " → ", ((argument.0))))`

Refers to: https://github.com/pyroscope/rtorrent-ps/issues/60

See Dev notes below for further info.

**Comment by chros73** [comment]
**A. Dev notes:**
- add a multi-method for column rendering: `ui.column.render`
  - call those methods, order is determined by keys in the map as usual
  - keys in the map encode sorting + length + column title:  `sort:len:title`
  - chop rendered column title and contents to the specified length
- make chopping of columns UTF8-aware: `u8_chop` internal method
- make x-position of columns dynamic in the code (advance by header length)
- refactor existing columns into commands, to make everything configurable (`d.ui.‹name›`)
- modify colouring to work with certain columns

Add the following commands:
- `value=«number»[,«base»]`: converts a given number with the given base (or 10 as the default) to an integer value
- `string.map=text,{from,to},…` for columns that can only have couple of fixed values, e.g. throttle, unsafe_data, etc.
- `d.tracker_scrape.downloaded` scrape info
- `d.tracker_scrape.complete` scrape info
- `d.tracker_scrape.incomplete` scrape info
- `d.parent_dir` to get the name of the parent directory of a download 

- `convert.human_size` used in upload data, data size columns
- `convert.magnitude` used in scrape columns


- `d.ui.message`
- `d.ui.completion`
- `d.ui.ratio`
- `d.ui.uprate_tm`
- `d.ui.downrate_tm`

- `ui.column.render` multi-command to hold column definitions
- add event.view.hide/show multi command, and call them on view changes
  - `method.set_key = event.view.hide, ~log, ((print, ((ui.current_view)), " → ", ((argument.0))))`

**Comment by pyroscope** [comment]
BTW, using #L links with "master" is pretty useless, since lines changeover time. #L only makes sense with SHAs.

**Comment by chros73** [comment]
Sorry about the confusion, you're right, sometimes I'm in a rush (especially when I have to deal with documentation :) ). Fixed now.
