### ISSUE TITLE
Fix bugs in 'math.*' commands

### ISSUE THREAD

**Issue by pyroscope** [chros73/rtorrent-ps-ch#135]
Fix bugs in `math.*` commands (thx @pyroscope):
- `math.div`/`mod`: [fix division by zero](https://github.com/pyroscope/rtorrent-ps/commit/7715faff1b00a54b4990d28d3c2b50fa12bf3883)
- `math.avg`/`med`: [fix invalid char pointer comparison](https://github.com/pyroscope/rtorrent-ps/commit/9f1539ca847cb2dd0a25d78db1ca2517e72820a1)

Refers to: #71

**Comment by pyroscope** [comment]
Forgot to close?

**Comment by chros73** [comment]
:) No, issues are closed when they are merged into master, currently they are on develop. I need to finish docs for other issues at first.
Thanks for the fixes!
