### ISSUE TITLE
Upgrade to official rtorrent/libtorrent 0.9.7/0.13.7 releases

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent-ps-ch#139]
Upgrade to official rtorrent/libtorrent `0.9.7/0.13.7` releases:
- modify build script:
  - change official release version number
  - change git commit versions to also point to latest releases
  - set `only_git_lt_rt` variable to `false`
  - change URL of releases to point to github
  - add new package hashes
- modify patches:
  - modify version checks in `*_pyroscope.cc` files:
    - bump every unmerged changes by `1` to support possible `git` param in build script
  - remove merged patches
  - modify broken one(s) (due to removed files in releases)
  - rename them to "all" (to support "git" version as well)
  - modify the patch path in them (to be able to use with `-p1`)
- upload new binaries to bintray
- update docs:
  - make a note for merged commands in Manual (if there's any)
  - update Readme file

**Comment by chros73** [comment]
@pyroscope, do I see right (by just taking a look at github repos) that the new releases are based on master branches now instead of branch-0.9 branches?!
I have to check it...

**Comment by chros73** [comment]
@pyroscope, indded, no more cherry-picking: they're based on master branches!
The size of the diff between previous and latest releases:
- libtorrent: 165K
- rtorrent: 265K

**Comment by pyroscope** [comment]
097 is not a prio, I will let the dust settle 1st. We have this stuff for years anyway.

**Comment by chros73** [comment]
> I will let the dust settle 1st

@pyroscope , I understand your point, no worries, take your time.
Although I think there won't be any new official release in the near future (~0.5-1.0-1.5 years, 2032? :D ) for 2 reasons:
- feature-bind branch takes way more time than he thought
- he also have to deal with untrivial PRs (which could have gone into this release :( )

0.9.7 was released to be widely tested in the meantime.

> they're based on master branches!

If there was just only 1 purpose of my ch project than this is it! :)
We use master branches for ~2 years now, I personally "only" had 1 crash during this time (1 download couldn't finish - stuck at 99% - and it crashed the client during deletion) and haven't got crash report from users.

One more thing, I - hopefully :) - finished modding [build.sh](https://github.com/chros73/rtorrent-ps-ch/blob/master/build.sh) script, never want to touch it again :)
- I heavily revisited 2 times in the past half year
- it's clean as it can be: only the necessary stuff included
- it's really versatile, can be used for development as well
- vanilla build is completely separated, nobody cares about it (I personally don't :D )
- it compiles on Debian 7-10, all Ubuntu LTS distribs, and many other distros as well
- the only "ugly" thing is the 2 [chrpath](https://github.com/chros73/rtorrent-ps-ch/blob/2bb786b8e130dfb1a0f298621d458faba873cebc/build.sh#L496) commands, but there wasn't any better/working way, and what the heck: we are patching anyways :)
- note that I haven't included docker support in it (and I don't plan it in the near future)

**Comment by pyroscope** [comment]
The GitHub answer to the whole release train thing, especially "deal with PRs", is adding members to a project too big for one person. Fat chance though.
