### ISSUE TITLE
Help with configuring some UI columns in collapsed view

### ISSUE THREAD

**Issue by TheBloke** [chros73/rtorrent-ps-ch#142]
Hey @chros73 thanks for all your work improving rtorrent.

I'm currently running 1.7.3-0.9.7, but will soon upgrade to the latest.

I really like the compact/collapsed UI view, however I feel it is missing some useful information.   Ideally I'd like to be able to see all the info I need in collapsed view, and not need the status lines at the bottom for anything.

Would you mind helping me to make the following changes?  I have read the rtorrent-PS docs regarding the Extended Canvas and how to customise it.  But my rtorrent scripting knowledge is limited, and I don't have pyroadmin set up fully to be able to see the default column definitions (I've not looked at configuring scgi yet).  

So I wondered if you might be able to tell me the config I need to do the following changes?

* Change the progress column to a %, rather than the dots
* Add an ETA column (only needs to apply for downloads)
* Add a total downloaded amount column (in MB or GB) - like there already is for uploaded
* Make the column headers bold white - I find it quite hard to read them in their current light-grey

If you were able to help save me some time on this I'd be most grateful.

Thanks in advance.

**Comment by chros73** [comment]
Hi there!

>  I have read the rtorrent-PS docs regarding the Extended Canvas

Unfortunately our project diverged in this regard and I didn't have the time so far to go through the changes, and I'm not sure yet whether I like the way it was created.
Here's the short docs for the [extended canvas](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/Manual.rst#uicolumnrender) of ch version.

> I don't have pyroadmin set up fully to be able to see the default column definitions

It won't even work with it at this point.

**Comment by chros73** [comment]
> Make the column headers bold white

Theming, that's the [line](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/color_scheme256-happy_pastel.rc#L10) you're looking for.

And this is how you can rotate through the different themes:
- [definitions](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L5)
- [keyboard shortcut](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L370)

> Change the progress column to a %, rather than the dots

[It's easy](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/Manual.rst#id3) as well, use: `ui.style.ratio.set=0`

> Add a total downloaded amount column (in MB or GB)

```ini
# Add Downloaded data (⊻) before Selected data size (✇) column
method.set_key = ui.column.render, "850:6:   ⊻  ", ((if, ((d.down.total)), ((convert.human_size, ((d.down.total)), (value, 0) )), ((cat, "   ·  "))))
```

> Add an ETA column (only needs to apply for downloads)

You can't do this with ps-ch for now, there's no command exposed for elapsed_time yet, all the other time columns are hardcoded (due to coloring support).
If I'll have time I'll implement/backport it from rtorrent-ps.

**Comment by chros73** [comment]
About the ratio column: if you don't like the style, you can use [these commands](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L42) to "mimic" `d.get_ratio_float` and create a new column for it. :)

**Comment by TheBloke** [comment]
That's excellent, @chros73  thanks so much for the help.  Sorry for the basic questions, I missed the mention of ui.style.progress.set in the documentation.  So there was only one complex one, the downloaded data. 

If you were able to implement elapsed_time for the UI that'd be great.  But it's not the most important thing.

Thanks again for all your great work on rtorrent.  I will continue studying the docs and your sample config.

One last question:

>> I don't have pyroadmin set up fully to be able to see the default column definitions

> It won't even work with it at this point.

Do you mean that pyroadmin won't work at all with rtorrent-PS-CH?  Or just the --dump-rc I planned to use to get the column definitions? 

If pyroadmin won't work at all, does this mean that rutorrent / scgi won't work either?

I don't know if I am going to bother using rutorrent / scgi, because right now I am quite happy running rtorrent in screen or tmux (as I see you do yourself, as per your rtorrent-ps-ch-setup).  But I did have it on my To Do list to try rutorrent sometime, to see what it is like, so it would be good to know if it can work or not.

Thanks again.

**Comment by chros73** [comment]
> Or just the --dump-rc I planned to use to get the column definitions?

Only this won't work.

> I don't know if I am going to bother using rutorrent / scgi, because right now I am quite happy running rtorrent in screen or tmux (as I see you do yourself, as per your rtorrent-ps-ch-setup). 

That's correct, I don't use any other utils for it, except for pyrocore and the helper scripts in my setup project. If only 1 HDD (partition) isn't an issue for you then try it out. :)

**Comment by chros73** [comment]
> Or just the --dump-rc I planned to use to get the column definitions?

Now it should work with the [new release](https://github.com/chros73/rtorrent-ps-ch/releases) as well.

All the 3 asked command are implemented:
- `d.eta.time` : [usage](https://github.com/chros73/rtorrent-ps-ch_setup/blob/31b49a1b1bf7c649aab6e8baa6d8296dc5f020fc/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L205)
- [numeric progress](https://github.com/chros73/rtorrent-ps-ch_setup/blob/31b49a1b1bf7c649aab6e8baa6d8296dc5f020fc/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L50) : [usage](https://github.com/chros73/rtorrent-ps-ch_setup/blob/31b49a1b1bf7c649aab6e8baa6d8296dc5f020fc/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L233)
- [numeric ratio](https://github.com/chros73/rtorrent-ps-ch_setup/blob/31b49a1b1bf7c649aab6e8baa6d8296dc5f020fc/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L46) : [usage](https://github.com/chros73/rtorrent-ps-ch_setup/blob/31b49a1b1bf7c649aab6e8baa6d8296dc5f020fc/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L238)
