### ISSUE TITLE
Invalid key in ~/test/rtorrent.d/05-rt-ps-columns.rc:18

### ISSUE THREAD

**Issue by billlllllll** [chros73/rtorrent-ps-ch#143]
rtorrent: Failed to parse command line option: Error in option file: /home/torrent/test/rtorrent.rc:50: Error in option file: /home/torrent/test/rtorrent.d/.import.rc:3: Error in option file: ~/test/rtorrent.d/05-rt-ps-columns.rc:18: Invalid key.

I first installed rtorrent-ps (rTorrent PS-1.1-29-g78a68a0 0.9.6/0.13.6) and successfully used it.
I then cloned https://github.com/chros73/rtorrent-ps-ch.git and built it with './build.sh ch'.
I also updated pyroscope as stated in the documentation.
Running ~/test/start gives the error above

**Comment by chros73** [comment]
Unfortunately it's a ["known" issue](https://github.com/chros73/rtorrent-ps-ch/issues/142#issuecomment-406853371), if you want to use pyroscope's setup then you're forced to use rtorrent-ps for now.

**Comment by billlllllll** [comment]
Fair enough, but how do I use your fork properly then?
I couldn't find anything in the documentation I missed or did wrong to get a proper setup.
Could you please point me to the missing steps to get rtorrent-ps-ch running?

Thanks in Advance

**Comment by chros73** [comment]
Let's see:
- if you use only 1 partition of HDD/SSD for data storage then you can use [rtorrent-ps-ch_setup](https://github.com/chros73/rtorrent-ps-ch_setup/)
- if not then you can take a look at the rtorrent configs in that setup:
  - [main config](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc) file (values, variables)
  - [engine config](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent.rc) (moving data, etc)
  - [ps-ch config](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc) (ps-ch related settings)

**Comment by billlllllll** [comment]
So just to clarify, if I want to use rtorrent-ps-ch instead of rtorrent-ps (basically as drop-in), then I have to write my own config based on the rtorrent-ps config but with slightly different (older?) syntax, yes?

I'm a little confused here, because rtorrent-ps-ch for me suggests that it is based on rtorrent-ps and only contains improvements similar to rtorrent-ps for rtorrent while still maintaining backwards compatibility.
Could you point me to some documentation explaining the differences in rtorrent-ps-ch syntax vs rtorrent-ps syntax?

Thanks again

**Comment by chros73** [comment]
> rtorrent-ps-ch for me suggests that it is based on rtorrent-ps and only contains improvements similar to rtorrent-ps for rtorrent while still maintaining backwards compatibility.

That was the case up until the last ps-ch release that happened before (!) the latest ps release: that's why the differences for now.

>  if I want to use rtorrent-ps-ch instead of rtorrent-ps (basically as drop-in), then I have to write my own config based on the rtorrent-ps config but with slightly different (older?) syntax, yes?
Could you point me to some documentation ...

Different syntax, not older :) But basically yes, the [canvas configuration is different](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/Manual.rst#extended-canvas-explained) and newer commands of ps are missing.

Btw, I started to look into the changes made to ps since last ps-ch release, I'll let you know how it goes within couple of days.

**Comment by chros73** [comment]
[1.8.1-0.9.7](https://github.com/chros73/rtorrent-ps-ch/releases) is released.
