### ISSUE TITLE
Segfault with 1.8.3/0.9.7

### ISSUE THREAD

**Issue by billlllllll** [chros73/rtorrent-ps-ch#159]
Caught Segmentation fault, dumping stack:
/home/torrent/bin/rtorrent() [0x413758]
/lib64/libpthread.so.0(+0x10bb0) [0x7f4368212bb0]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(+0x9a6da) [0x7f43695a26da]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(+0x985e3) [0x7f43695a05e3]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(+0x959cb) [0x7f436959d9cb]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(+0x95f9d) [0x7f436959df9d]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(+0x2c263) [0x7f4369534263]
/home/torrent/lib/rtorrent-ps-ch-1.8.3-0.9.7/bin/../lib/libtorrent.so.20(_ZN7torrent11thread_base10event_loopEPS0_+0x170) [0x7f43695811b0]
/home/torrent/bin/rtorrent() [0x41217b]
/lib64/libc.so.6(__libc_start_main+0xf0) [0x7f43675da600]
/home/torrent/bin/rtorrent() [0x412de9]

[7118427.688772] rtorrent main[11418]: segfault at 81 ip 00007fef6b405cb9 sp 00007ffc66568a90 error 4 in libgcc_s-5.5.0.so.1[7fef6b3f7000+16000]
[7120297.049836] rtorrent main[8477]: segfault at 81 ip 00007f0649a90cb9 sp 00007ffe7d4a9f10 error 4 in libgcc_s-5.5.0.so.1[7f0649a82000+16000]

**Comment by billlllllll** [comment]
Here is a backtrace done with gdb:

Thread 1 "rtorrent main" received signal SIGSEGV, Segmentation fault.
0x0000000000000081 in ?? ()
(gdb) where
#0  0x0000000000000081 in ?? ()
#1  0x00007f10c4b4c6dd in torrent::DhtTransactionSearch::~DhtTransactionSearch (this=0x573619c0, __in_chrg=<optimized out>) at dht_transaction.cc:309
#2  0x00007f10c4b4a5e3 in torrent::DhtTransactionFindNode::~DhtTransactionFindNode (this=0x573619c0, __in_chrg=<optimized out>) at dht_transaction.h:367
#3  torrent::DhtTransactionFindNode::~DhtTransactionFindNode (this=0x573619c0, __in_chrg=<optimized out>) at dht_transaction.h:367
#4  0x00007f10c4b479cb in torrent::DhtServer::failed_transaction (this=this@entry=0x2088b20, itr={first = 1348235919781527724, second = 0x573619c0}, quick=quick@entry=false) at dht_server.cc:684
#5  0x00007f10c4b47f9d in torrent::DhtServer::receive_timeout (this=0x2088b20) at dht_server.cc:939
#6  0x00007f10c4ade263 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/5.5.0/functional:2267
#7  torrent::thread_main::call_events (this=<optimized out>) at thread_main.cc:82
#8  0x00007f10c4b2b1e1 in torrent::thread_base::event_loop (thread=0x1e02ff0) at thread_base.cc:151
#9  0x000000000041217b in main (argc=6, argv=0x7ffcbe06eb98) at main.cc:509

**Comment by chros73** [comment]
Interesting.
But please report upstream issues upstream (this one in [libtorrent](https://github.com/rakshasa/libtorrent/)), thanks!
