### ISSUE TITLE
"rtorrent main" received signal SIGSEGV

### ISSUE THREAD

**Issue by billlllllll** [chros73/rtorrent-ps-ch#160]
Hello,

Thread 1 "rtorrent main" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) where
#0  0x0000000000000000 in ?? ()
#1  0x00007fbff59c8819 in torrent::DhtServer::find_node_next (this=this@entry=0x179a540, transaction=transaction@entry=0x54dd3120) at dht_server.cc:498
#2  0x00007fbff59c90fe in torrent::DhtServer::parse_find_node_reply (this=this@entry=0x179a540, transaction=transaction@entry=0x54dd3120, nodes=...) at dht_server.cc:466
#3  0x00007fbff59c92e6 in torrent::DhtServer::process_response (this=this@entry=0x179a540, id=..., sa=sa@entry=0x7ffd3b6763e0, response=...) at dht_server.cc:397
#4  0x00007fbff59ca76e in torrent::DhtServer::event_read (this=0x179a540) at dht_server.cc:793
#5  0x00007fbff596fb2a in torrent::PollEPoll::perform (this=this@entry=0x1516040) at poll_epoll.cc:185
#6  0x00007fbff596fbbd in torrent::PollEPoll::do_poll (this=0x1516040, timeout_usec=<optimized out>, flags=<optimized out>) at poll_epoll.cc:224
#7  0x00007fbff59ac164 in torrent::thread_base::event_loop (thread=0x1512ff0) at thread_base.cc:174
#8  0x000000000041217b in main (argc=6, argv=0x7ffd3b677598) at main.cc:509

How to tell if it is an upstream issue or not?
Thanks

**Comment by billlllllll** [comment]
Here another one:
Thread 1 "rtorrent main" received signal SIGSEGV, Segmentation fault.
0x0000000000000081 in ?? ()
(gdb) where
#0  0x0000000000000081 in ?? ()
#1  0x00007ff752a2f6dd in torrent::DhtTransactionSearch::~DhtTransactionSearch (this=0x55c9b130, __in_chrg=<optimized out>) at dht_transaction.cc:309
#2  0x00007ff752a2d5e3 in torrent::DhtTransactionFindNode::~DhtTransactionFindNode (this=0x55c9b130, __in_chrg=<optimized out>) at dht_transaction.h:367
#3  torrent::DhtTransactionFindNode::~DhtTransactionFindNode (this=0x55c9b130, __in_chrg=<optimized out>) at dht_transaction.h:367
#4  0x00007ff752a2a206 in torrent::DhtServer::add_transaction (this=this@entry=0x267b540, transaction=transaction@entry=0x55c9b130, priority=priority@entry=2) at dht_server.cc:638
#5  0x00007ff752a2a723 in torrent::DhtServer::find_node_next (this=this@entry=0x267b540, transaction=transaction@entry=0x55c811f0) at dht_server.cc:496
#6  0x00007ff752a2b0fe in torrent::DhtServer::parse_find_node_reply (this=this@entry=0x267b540, transaction=transaction@entry=0x55c811f0, nodes=...) at dht_server.cc:466
#7  0x00007ff752a2b2e6 in torrent::DhtServer::process_response (this=this@entry=0x267b540, id=..., sa=sa@entry=0x7ffcf33aab20, response=...) at dht_server.cc:397
#8  0x00007ff752a2c76e in torrent::DhtServer::event_read (this=0x267b540) at dht_server.cc:793
#9  0x00007ff7529d1b2a in torrent::PollEPoll::perform (this=this@entry=0x23f7040) at poll_epoll.cc:185
#10 0x00007ff7529d1bbd in torrent::PollEPoll::do_poll (this=0x23f7040, timeout_usec=<optimized out>, flags=<optimized out>) at poll_epoll.cc:224
#11 0x00007ff752a0e164 in torrent::thread_base::event_loop (thread=0x23f3ff0) at thread_base.cc:174
#12 0x000000000041217b in main (argc=6, argv=0x7ffcf33abcd8) at main.cc:509

**Comment by chros73** [comment]
:) This one is also an upstream issue: they are (including the previous closed one) all related to DHT.
Can you create tickets upstream about them? Thanks

> How to tell if it is an upstream issue or not?

I understand that it can be hard to tell:
- if there's no patch relating to the issue you want to raise
  - since there's no DHT related patch it means it's upstream

**Comment by chros73** [comment]
Also, if you want to make sure, you can build vanilla rtorrent and try to recreate the issue.
