### ISSUE TITLE
Add support for vim keybindings

### ISSUE THREAD

**Issue by Atreus-Tantalus** [chros73/rtorrent-ps-ch#161]

**Comment by chros73** [comment]
Personally I'm not interested in this, but if you are willing to work on it then I'll be happy to merge a pull request that can be backported to rtorrent as well.
Here's a [patch for 0.9.6](https://aur.archlinux.org/cgit/aur.git/tree/rtorrent-0.9.6_vi_keybinding_tjwoosta.patch?h=rtorrent-vi-color) that can be a base for this. I can also help you with guidelines, tips, etc.
