### ISSUE TITLE
pgup, pgdown not working?

### ISSUE THREAD

**Issue by pahtii7T** [chros73/rtorrent-ps-ch#162]
Just migrated from rtorrent-ps, I can't seem to get pageup & pagedown working.

Any deas?

**Comment by pahtii7T** [comment]
and also "t" does not work to sort by tracker?

**Comment by chros73** [comment]
[keys def](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L446)
[t key](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L371)
Take a look at tge rest of thw config filw as well and/or setup.
