### ISSUE TITLE
Cannot make install on Debian 9

### ISSUE THREAD

**Issue by joydashy** [chros73/rtorrent-ps-ch#163]
time nice -n 19 ./build.sh ch

> 
> Env for building rTorrent-PS-CH 1.8.3 0.9.7/0.13.7 into /home/redbull/lib/rtorrent-ps-ch-1.8.3-0.9.7
> 
> optimize_build="yes"
> export PKG_CONFIG_PATH="/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7/lib/pkgconfig"
> export LDFLAGS="-Wl,-rpath,'$$ORIGIN/../lib' -Wl,-rpath,'$$ORIGIN/../lib/rtorrent-ps-ch/lib'"
> export CFLAGS="-march=native -pipe -O2 -fomit-frame-pointer"
> export CXXFLAGS="-march=native -pipe -O2 -fomit-frame-pointer"
> 
> export build_dir="/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7"
> pkg_inst_dir="/opt/rtorrent-ps-ch-1.8.3-0.9.7"
> 
> export curl_opts="-sLS"
> export make_opts="-j4"
> export cfg_opts=""
> export cfg_opts_lt=""
> export cfg_opts_rt=""
> 
> ERROR: Current '1.8.3' version is already built in '/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7', it has to be removed manually before a new compilation.
> 
> real 0.444      user 0.105      sys 0.275       pcpu 85.66

sudo ./build.sh install

> ERROR: Compilation hasn't been finished, try it again.

Running rtorrent from ~/bin seems to work, so just the make install is failing somehow.

**Comment by chros73** [comment]
The error message says all: you already built one in that directory.

**Comment by joydashy** [comment]
Not sure what you mean, this task is the one failing:
> sudo ./build.sh install

Stating:

> Compilation hasn't been finished

**Comment by chros73** [comment]
> Not sure what you mean

I've been referring to this message:
```ERROR: Current '1.8.3' version is already built in '/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7', it has to be removed manually before a new compilation.```

> Compilation hasn't been finished

[This message means](https://github.com/chros73/rtorrent-ps-ch/blob/master/build.sh#L703) that `version-info.sh` file is missing from the build dir for whatever reason: `/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7'

Just delete `/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7' directory and start again.
Which Linux distro do you use?

**Comment by joydashy** [comment]
But, I don't want to start again, I am trying to run the install script, after the successful build, literally following these instructions:
https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/DebianInstallFromSourceTheEasyWay.rst

That's why I run into this issue.

(Debian 9.9)

**Comment by chros73** [comment]
Do you have this file?
`/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7/version-info.sh`

**Comment by joydashy** [comment]
Yes

> rt_ps_ch_version='1.8.3'
> rt_ps_ch_rt_version='0.9.7'
> rt_ps_ch_lt_version='0.13.7'
> rt_ps_ch_revision='20190613'
> rt_ps_ch_cares_version='1.14.0'
> rt_ps_ch_curl_version='7.61.1'
> rt_ps_ch_xmlrpc_tree='stable'
> rt_ps_ch_xmlrpc_rev='2985'
> optimized_build='yes'

**Comment by chros73** [comment]
Hmmm, interesting. It definitely [doesn't find that file](https://github.com/chros73/rtorrent-ps-ch/blob/master/build.sh#L703) in the `$build_dir` directory.
Edit the `build.sh` file and put this debug line between line 702 and 703 (below `install()`):
`echo "$build_dir/$ver_info_filename"`

What's the output when you run `sudo ./build.sh install`? It should print out a completely directory/file. If that's the case then it's a `sudo` problem on recent Debian 9.

**Comment by joydashy** [comment]
Output:

> /root/lib/rtorrent-ps-ch-1.8.3-0.9.7/version-info.sh
ERROR: Compilation hasn't been finished, try it again.

**Comment by chros73** [comment]
> /root/lib/rtorrent-ps-ch-1.8.3-0.9.7/version-info.sh

Yes, sudo issue on Debian as the manual states: ["More hint about sudo for Debian."](https://github.com/chros73/rtorrent-ps-ch/blob/master/docs/DebianInstallFromSourceTheEasyWay.rst#install-it-into-system)

[Try out this](https://github.com/chros73/rtorrent-ps-ch_setup/commit/86ee569828950c7494846deb119a6a312a47feae#diff-484a7c3eab85aad0e827b45a3619baf0), it should solve your issue.

**Comment by joydashy** [comment]
Seems to work now, althought it says something about Failing...:

> Checking links:
> 
> /usr/local/bin/rtorrent -> ../lib/rtorrent-ps-ch/bin/rtorrent
> /usr/local/lib/rtorrent-ps-ch -> /opt/rtorrent-ps-ch
> /opt/rtorrent-ps-ch -> rtorrent-ps-ch-1.8.3-0.9.7
> 
> Check that static linking worked: FAIL
> 
> Suspicious library paths are:
>         libxmlrpc_util.so.4 => /usr/local/lib/libxmlrpc_util.so.4 (0x00007fb2fe2da000)
> 
> Dependency library paths:
>         libcurl.so.4 => ../lib/rtorrent-ps-ch/lib/libcurl.so.4 (0x00007fb300dff000)
>         libtorrent.so.20 => ../lib/libtorrent.so.20 (0x00007fb300ac7000)
>         libxmlrpc_server.so.3 => ../lib/libxmlrpc_server.so.3 (0x00007fb3008c0000)
>         libxmlrpc.so.3 => ../lib/libxmlrpc.so.3 (0x00007fb3006a4000)
>         libxmlrpc_xmlparse.so.3 => ../lib/libxmlrpc_xmlparse.so.3 (0x00007fb300493000)
>         libxmlrpc_xmltok.so.3 => ../lib/libxmlrpc_xmltok.so.3 (0x00007fb300274000)
>         libxmlrpc_util.so.3 => ../lib/rtorrent-ps-ch/lib/libxmlrpc_util.so.3 (0x00007fb30006e000)
>         libcares.so.2 => ../lib/rtorrent-ps-ch/lib/../lib/libcares.so.2 (0x00007fb2fedff000)
>         libxmlrpc_util.so.4 => /usr/local/lib/libxmlrpc_util.so.4 (0x00007fb2fe2da000)

**Comment by chros73** [comment]
> Suspicious library paths are:
> libxmlrpc_util.so.4 => /usr/local/lib/libxmlrpc_util.so.4 (0x00007fb2fe2da000)

It says that `libxmlrpc_util.so.4` is linked as well from the main system - while it shouldn't -, while `libxmlrpc_util.so.3` is also linked from the `../lib/` directory. 

Just delete the original build folder `/home/rb/lib/rtorrent-ps-ch-1.8.3-0.9.7` and start over again with:
`time nice -n 19 ./build.sh ch`

If you see the same FAIL error at the end of this step (before `sudo ./build.sh install`) then something is not right on your system (e.g. you have [xmlrpc-c](https://packages.debian.org/search?keywords=xmlrpc-c&searchon=names&suite=stable&section=all) package(s) installed).

**Comment by joydashy** [comment]
Ok, thanks for your help, hope it helps others on Debian.

**Comment by chros73** [comment]
I modified the title of this issue, I'm glad it worked.
