### ISSUE TITLE
Please add libtorrent DHT patch.

### ISSUE THREAD

**Issue by mhertz** [chros73/rtorrent-ps-ch#166]
I regularly have a DHT error where rtorrent-ps-ch crashes, often right at the download is finished, but othertimes at random times during download. It always comes with magnets added directly to rtorrent. I found a couple libtorrent github issues about this where it seems several are affected and happens at rtorrent 0.9.7 and up, it seems. One of the issue-reports included a fix/patch so the crashes stops, so I wanted to ask if you would consider adding this?

https://github.com/rakshasa/rtorrent/issues/760
https://github.com/rakshasa/libtorrent/issues/141 (Patch included in this thread and applies properly to current libtorrent).

Thanks in advance for reading/considering this :)

-Martin.

**Comment by chros73** [comment]
Hi!

> ... often right at the download is finished, but othertimes at random times during download ...
> One of the issue-reports included a fix/patch so the crashes stops, so I wanted to ask if you would consider adding this?

Have you tried it out by yourself if it indeed fixes your problem?
They only talk about the first part in the issue.

**Comment by mhertz** [comment]
Figures I now have a hard time catching the error now when specifically looking for it, lol :)

The error happens almost only at the end of a download and I only got it once, maybe twise in other scenario.

I made this request because I didn't want to have to use vanilla rtorrent with that patch applied, so hence this ticket, but I now see it's no problem to include that patch with the other patches in rtorrent-ps-ch, and rebuild it, so can continue using your version now with also that patch.

I'm sure the patch works, because it removes the line showing and giving the critical/crashing error and instead just logs it, but i've just started 4 torrents without catching it. I don't torrent very much and just picked up rtorrent again a couple of weeks ago in place of deluge-console(after finally getting a VPN with portforwarding-support, which rtorrent needs for proper dht function).

Anyway, you can think about it possibly, or atleast have it in the back of your mind that a solution exist if you get more reports about this. Also, it properly would be best for me to first try get it included in libtorrent itself if possible.

Thanks alot for your great work Chros, much appreciated!

-Martin.

**Comment by chros73** [comment]
> I now see it's no problem to include that patch with the other patches in rtorrent-ps-ch, and rebuild it

Great! :)

> I'm sure the patch works, because it removes the sole line showing and giving the critical/crashing error and instead just logs it, but i've today started/finished 5 torrents without catching it.

:) I took a look what the patch does, but I'm not convinced that's a legit solution, who knows what other issues it can raise (since I don't know much about how DHT is implemented/suppose to work).
That's why I didn't say yes to your request.

I used public torrents with rtorrent couple of years ago, for about a half - 1 year, and I didn't notice any issues with it, but that doesn't mean I didn't have it :) After that I was forced to quit using public torrents (see below).

> finally getting a VPN with portforwarding-support,

Which one did you pick? I use AirVPN and it's pretty good, but not the cheapest.
And if you haven't seen [this wiki page](https://github.com/rakshasa/rtorrent/wiki/VPN-with-Traffic-Splitting) ...

> Also, it properly would be better fitted directly in libtorrent itself.

Use it for 1 month and report back. But at then, if you think it doesn't break anything else, just create a pull request for it in libtorrent :)

> Thanks alot for your great work Chros, much appreciated!

Tons of work was done by pyroscope, so it's not just me :)
Enjoy!

**Comment by mhertz** [comment]
Thanks for your reply Chros! Hmm, I didn't think of that honestly, I didn't think there where any breakage-risc but you're right, and I'm no DHT-expert either. Anyway, good idea to let it run in a
month and if no issues then request it directly in libtorrent. 

As for VPNs I would have chosen AirVPN if not considering price much, but I started with PIA some years ago because cheapest available at the time and no issues, but then fell over a cheap lifetime subscription to tigervpn which though didn't support portforwarding which made me change to deluge, but now I have another lifetime subscription with windscribe which includes portforwarding and hence me coming back to the "fold" again :) The first lifetime was 40 bucks and the latter which I only use now was 55 bucks. I got the later a year ago about, but they at the time only had planned support for portforwarding, and just recently included that and also stopped selling such lifetime subscriptions anymore. Of course I know lifetime doesn't should be taken literally and only is for how long the company exists or change policy etc but still to me seemed like a great bargain. 

Thanks, I do know about namespaced-openvpn from your wiki entry and changed over to that method of split-tunneling when first saw it :) Love that solution and have preached about it and posted setup-instructions on other forums e.g. deluge-forum. BTW, Slingamn, the dev of that nice script was the person, besides me, which gave the patch a like in that issue-ticket. 

Thanks again Chros, and of course I owe big thanks additionally also to rakshasa and Pyroscope, - without the three of you, the torrent-client scene would indeed be a much sadder place to be in / "tinker" with :)

**Comment by chros73** [comment]
> The first lifetime was 40 bucks and the latter which I only use now was 55 bucks.

That's pretty good deal, especially if they can provide high bandwidth as well (>=8 MB/s).

> BTW, Slingamn, the dev of that nice script was the person, besides me, which gave the patch a like in that issue-ticket.

:D Oh, so that's why that username was so familiar, stupid me ... :)
