### ISSUE TITLE
Make f=filter work with multiple conditions

### ISSUE THREAD

**Issue by antonioantunes** [chros73/rtorrent-ps-ch#169]
Hi,

The command "f=\<condition>" works fine for a single condition, eg: 
`f=is_active=no
`

However it would be useful to be possible to filter with multiple conditions, eg.
`f="is_active=no is_ghost=yes"
`

I tried to implement this but was unable to get it to work, because this is passed to rtcontrol in a way that both conditions are part of the same parameter, like running this way:

```
rtorrent@vm:~$ rtcontrol "is_active=no is_ghost=yes"
ERROR    Bad boolean value 'no is_ghost=yes' in u'no is_ghost=yes' (expected one of '+' '1' 't' 'y' 'yes' 'true', or 'false' 'no' 'f' '-' 'n' '0')
INFO     Total time: 0.015 seconds.
```

While splitting it in two parameters would give good results:

```
rtorrent@vm:~$ rtcontrol is_active=no is_ghost=yes
INFO     Dumped 0 out of 28 torrents.
INFO     Total time: 0.015 seconds.
```

But I do not know the best way of doing this in rtorrent. Any advice?

Also I am not sure if this would be best handled at rtorrent-ps or rtorrent-ps-ch, please let me know if it can be handled here.

Thanks!

**Comment by chros73** [comment]
Hi!

`f=` is [defined in the config file](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.pyroscope/rtorrent-ps.rc#L161) (by pyroscope), and as we can see it just accepts 1 parameter (`$argument.0=`).

You can create another method e.g. `f2` for yourself that will accept 2 params, e.g. (note I haven't tested this):
```ini
method.insert = f2,simple|private,"execute.nothrow=\"$cat=$pyro.bin_dir=,rtcontrol\",--detach,-qV,\"$cat=$argument.0=,\\\" \\\",$argument.1=\""
```

And you can use it like this:
```ini
f2=is_active=no,is_ghost=yes
```
