### ISSUE TITLE
Fix getting xmlrpc-c in build.sh due to shutdown of Bintray

### ISSUE THREAD

**Issue by darkalchemy** [chros73/rtorrent-ps-ch#170]
Hello,

The build script is failing on extracting the xmlrpc-c file. After a little debugging, I get 'Forbidden!' when downloading from this link
https://dl.bintray.com/chros73/rtorrent-ps-ch/pool/x/xmlrpc-c-stable/xmlrpc-c-stable-2985-src.tgz so it's just creating a 10 byte file.

Could you look into this when you have a moment?

Thanks

**Comment by moex3** [comment]
I had the same problem. The solution is, to edit the build.sh script like this:

```diff
diff --git a/build.sh b/build.sh
index 04851c7..f6ec980 100755
--- a/build.sh
+++ b/build.sh
@@ -206,7 +206,7 @@ tarballs+=("https://github.com/rakshasa/rtorrent/releases/download/v$rt_version/
 tarballs+=("https://github.com/rakshasa/rtorrent/releases/download/v$rt_version/rtorrent-$rt_version.tar.gz")

 # Get xmlrpc-c from svn if it's not mirrored
-[[ ! "$xmlrpc_rev" =~ ^(2985|2912|2775)$ ]] && xmlrpc_svn_url="http://svn.code.sf.net/p/xmlrpc-c/code/$xmlrpc_tree@$xmlrpc_rev"
+xmlrpc_svn_url="http://svn.code.sf.net/p/xmlrpc-c/code/$xmlrpc_tree@$xmlrpc_rev"


 # Source package md5 hashes
```

So it will always check it out from svn.

**Comment by chros73** [comment]
Bintray service has been shutdown, so I uploaded the used `xmlrpc-c` source to github instead.
Let me know if it fixes the issue.

**Comment by darkalchemy** [comment]
Thanks @chros73. I appreciate all you do.
